language: go
sudo: required
dist: trusty

go:
  - 1.8.x

go_import_path: github.com/kubernetes-incubator/cri-tools

services:
  - docker

before_install:
  - hack/install-docker.sh
  - hack/install-kubelet.sh

install:
  - make install.tools


script:
  - make
  - make lint
  - make gofmt
  - sudo env PATH=$PATH GOPATH=$GOPATH hack/run-critest.sh

