name: cri-tools e2e test
on: [push, pull_request]
jobs:
  test-e2e:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/kubernetes-sigs/cri-tools

      - name: Run e2e test
        run: |
          set -e
          sudo -E go env
          echo $PATH
          sudo -E echo $PATH

        working-directory: src/github.com/kubernetes-sigs/cri-tools
